### ISSUE TITLE
Error on query.

### ISSUE THREAD

**Issue by GrumpyCrouton** [GrumpyCrouton/GrumpyPDO#14]
## Expected Behavior
Propery query returned

## Actual Behavior
Error: Internal Server Error PDO::query(): SQLSTATE[HY000]: General error: constructor arguments must be passed as an array

## Steps to Reproduce the Problem

  1. Run a query (all()) with no variables; `$facilities = $db->all("SELECT uid, name FROM rc_facilities");`

**Comment by colshrapnel** [comment]
I cannot reproduce the behavior.

    include 'grumpypdo.php';
    $db = new GrumpyPdo("127.0.0.1","root", "", "test");
    $db->query("create temporary table if not exists rc_facilities (uid int, name varchar(255))");
    $db->query("insert into rc_facilities values (1, 'grumpy')");
    var_dump($db->all("SELECT `uid`, `name` FROM `rc_facilities`"));

outputs 

```
array(1) {
  [0]=>
  array(2) {
    ["uid"]=>
    int(1)
    ["name"]=>
    string(6) "grumpy"
  }
}
```

but no error.

**Comment by GrumpyCrouton** [comment]
@colshrapnel Very interesting. I have no idea why I am getting this error

**Comment by GrumpyCrouton** [comment]
Cannot reproduce error, false positive?
