### ISSUE TITLE
native functions

### ISSUE THREAD

**Issue by dextel2** [GrumpyCrouton/GrumpyPDO#15]
## Expected Behavior
How do I call the native member functions of PDO Class, such as `lastInsertId()`?

**Comment by GrumpyCrouton** [comment]
@dextel2 You can do everything with this class that you can do with the native class, so let's say you initialize the class by: 

`$db = new GrumpyPDO("localhost", "", "", "");`

Well, if you want to use lastInsertId(), you would simply call `$db->lastInertId();`.

Also, sorry for the delayed response, I didn't see this post until just now.
